name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "f0726a20edb046dbb247f347769098cc" }
]

[triggers]
crons = [ ]
